api:
  base_url: "https://datosabiertos.bcie.org/api/3/action/datastore_search"
  resource_id: "ce88a753-57f5-4266-a57e-394600c8435d"
  limit: 32000

data:
  raw_path: "data/01-raw/aprobaciones_bcie.csv"
  processed_path: "data/02-preprocessed/aprobaciones_limpias.csv"

  # Mapeo exacto de las columnas
  column_renames:
    "ANIO_APROBACION": "Anio_Origen"
    "MONTO_BRUTO_USD": "Monto_Aprobado"
    "PAIS": "Pais"
    "SECTOR_INSTITUCIONAL": "Sector_Economico"

  # Columnas internas
  date_col: "Fecha_Aprobacion"
  value_col: "Monto_Aprobado"
  group_col: "Pais"

runs:
  output_root: "data/04-predictions/runs"

model:
  output_path: "data/04-predictions/"
  output_name: "aprobaciones_clusters"

  features:
    - "Monto_Aprobado"
    - "CANTIDAD_APROBACIONES"

  log_transform_feature: "Monto_Aprobado"
  scaler: "standard"

  # HDBSCAN Parameters
  min_cluster_size: 15
  min_samples: 5
  metric: "euclidean"
  cluster_selection_epsilon: 0.0

  # Validation
  bootstrap_n: 20

  # Plots (Deprecated/Legacy logic)
  plots_path: "data/05-plots/"
